import React, { useState,useRef ,useEffect} from 'react'
import Image from 'next/image'
import styles from '../styles/Navbar.module.css'
import { IoBookmarkOutline } from 'react-icons/io5'
import { IoIosNotificationsOutline } from 'react-icons/io'
import Head from 'next/head';
import Link from 'next/dist/client/link'
import { signOut } from "next-auth/client"
export default function Layout({ children,auth }) {
    const [showDetails, setShowDetails] = useState(false)

    return (
        <>
            <Head>
                <title>Poemezery - Social media for poems</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav>
                <div className={styles.navbar}>
                    <h3><Link href='/'>Poemezery</Link></h3>
                    <form action='/' method='GET'>
                        <input placeholder='Search ...' type='text' />
                    </form>
                    {!auth ? <div className={styles.form}>
                        <Link href='/sign-in'><a className={styles.btn}>Login</a></Link>
                        <Link href='/sign-up'><a  className={styles.btn}>Get Started</a></Link>
                    </div> : <div className={styles.form}>
                        <div className='dropdown'>
                            <div className={styles.icons}><IoIosNotificationsOutline size={'30px'} /></div>
                            <div style={{ display: 'none' }} className={styles.secretSection}>
                                <p> Not new notifications yet</p>
                            </div>
                        </div>
                        <div className={styles.icons}><Link href='/bookmarks' ><IoBookmarkOutline size={'30px'} /></Link></div>
                        <div>
                            <Image  onMouseUp={() => setShowDetails(!showDetails)} src='/default_avatar.png' width='40px' height='40px' alt='avatar_image' />
                            <div onBlur={() => {setShowDetails(false);console.log('asda')}} style={showDetails ? { display: 'block' } : { display: 'none' }} className={styles.secretSection}>
                                <ul>
                                    <li><Link href='/my-poems'>Poems</Link></li>
                                    <li><Link href='/write-poem'>Write Poems</Link></li>
                                </ul>
                                <ul>
                                    <li><Link href='/my-app'>Profile</Link></li>
                                    <li><Link href='/settings'>Settings</Link></li>
                                    <li><Link type='button' onClick={()=>signOut({callbackUrl:'/'})}>Log out</Link></li>
                                </ul>
                            </div>
                        </div>
                    </div>}
                </div>
            </nav>
            <main>
                {children}
            </main>
            <footer className={styles.footer}>
                <ul>
                    <li><Link href='/about'>About</Link></li>
                    <li><Link href='/contact-us'>Contact us</Link></li>
                    <li><Link href='/privacy'>Privacy</Link></li>
                    <li><Link href='/tio'>Terms of services</Link></li>
                    <li><Link href='/'>Poems</Link></li>
                </ul>
            </footer>
        </>
    )
}
